/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TeacherService } from "../teacher.service";
import { TeacherCreateInput } from "./TeacherCreateInput";
import { Teacher } from "./Teacher";
import { TeacherFindManyArgs } from "./TeacherFindManyArgs";
import { TeacherWhereUniqueInput } from "./TeacherWhereUniqueInput";
import { TeacherUpdateInput } from "./TeacherUpdateInput";
import { AttendanceHistoryFindManyArgs } from "../../attendanceHistory/base/AttendanceHistoryFindManyArgs";
import { AttendanceHistory } from "../../attendanceHistory/base/AttendanceHistory";
import { AttendanceHistoryWhereUniqueInput } from "../../attendanceHistory/base/AttendanceHistoryWhereUniqueInput";

export class TeacherControllerBase {
  constructor(protected readonly service: TeacherService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Teacher })
  async createTeacher(
    @common.Body() data: TeacherCreateInput
  ): Promise<Teacher> {
    return await this.service.createTeacher({
      data: data,
      select: {
        createdAt: true,
        date: true,
        email: true,
        id: true,
        name: true,
        phone: true,
        role: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Teacher] })
  @ApiNestedQuery(TeacherFindManyArgs)
  async teachers(@common.Req() request: Request): Promise<Teacher[]> {
    const args = plainToClass(TeacherFindManyArgs, request.query);
    return this.service.teachers({
      ...args,
      select: {
        createdAt: true,
        date: true,
        email: true,
        id: true,
        name: true,
        phone: true,
        role: true,
        status: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Teacher })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async teacher(
    @common.Param() params: TeacherWhereUniqueInput
  ): Promise<Teacher | null> {
    const result = await this.service.teacher({
      where: params,
      select: {
        createdAt: true,
        date: true,
        email: true,
        id: true,
        name: true,
        phone: true,
        role: true,
        status: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Teacher })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTeacher(
    @common.Param() params: TeacherWhereUniqueInput,
    @common.Body() data: TeacherUpdateInput
  ): Promise<Teacher | null> {
    try {
      return await this.service.updateTeacher({
        where: params,
        data: data,
        select: {
          createdAt: true,
          date: true,
          email: true,
          id: true,
          name: true,
          phone: true,
          role: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Teacher })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTeacher(
    @common.Param() params: TeacherWhereUniqueInput
  ): Promise<Teacher | null> {
    try {
      return await this.service.deleteTeacher({
        where: params,
        select: {
          createdAt: true,
          date: true,
          email: true,
          id: true,
          name: true,
          phone: true,
          role: true,
          status: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/attendanceHistories")
  @ApiNestedQuery(AttendanceHistoryFindManyArgs)
  async findAttendanceHistories(
    @common.Req() request: Request,
    @common.Param() params: TeacherWhereUniqueInput
  ): Promise<AttendanceHistory[]> {
    const query = plainToClass(AttendanceHistoryFindManyArgs, request.query);
    const results = await this.service.findAttendanceHistories(params.id, {
      ...query,
      select: {
        checkIn: true,
        checkOut: true,
        createdAt: true,
        date: true,
        id: true,
        status: true,

        teacher: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/attendanceHistories")
  async connectAttendanceHistories(
    @common.Param() params: TeacherWhereUniqueInput,
    @common.Body() body: AttendanceHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attendanceHistories: {
        connect: body,
      },
    };
    await this.service.updateTeacher({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/attendanceHistories")
  async updateAttendanceHistories(
    @common.Param() params: TeacherWhereUniqueInput,
    @common.Body() body: AttendanceHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attendanceHistories: {
        set: body,
      },
    };
    await this.service.updateTeacher({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/attendanceHistories")
  async disconnectAttendanceHistories(
    @common.Param() params: TeacherWhereUniqueInput,
    @common.Body() body: AttendanceHistoryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      attendanceHistories: {
        disconnect: body,
      },
    };
    await this.service.updateTeacher({
      where: params,
      data,
      select: { id: true },
    });
  }
}
